### ISSUE TITLE
elmo_embeddings and char_embeddings 's size not match

### ISSUE THREAD

**Issue by jylee-xidian** [alexa/dstqa#5]
I cannot train model with the default config because of OOM,(one 2080TI)
So I have changed batch_size  to  16/12/20, the error logs:
`val_10_acc: 0.8400, val_11_acc: 0.7280, val_12_acc: 0.8179, val_13_acc: 0.6609, val_14_acc: 0.8139, val_15_acc: 0.7733, val_16_acc: 0.7936, val_17_acc: 0.6981, val_18_acc: 0.6922, val_19_acc: 0.6428, val_20_acc: 0.8478, val_21_acc: 0.8577, val_22_acc: 0.8610, val_23_acc: 0.6790, val_24_acc: 0.8293, val_25_acc: 0.7188, val_26_acc: 0.8647, val_27_acc: 0.8618, val_28_acc: 0.9418, val_0_acc: 0.6045, val_1_acc: 0.6465, val_2_acc: 0.6369, val_3_acc: 0.8242, val_4_acc: 0.8367, val_5_acc: 0.8481, val_6_acc: 0.7424, val_7_acc: 0.7051, val_8_acc: 0.7313, val_9_acc: 0.7766, val_10_acc: 0.8400, val_11_acc: 0.7280, val_12_acc: 0.8179, val_13_acc: 0.6609, val_14_acc: 0.8139, val_15_acc: 0.7733, val_16_acc: 0.7936, val_17_acc: 0.6981, val_18_acc: 0.6922, val_19_acc: 0.6428, val_20_acc: 0.8478, val_21_acc: 0.8577, val_22_acc: 0.8610, val_23_acc: 0.6790, val_24_acc: 0.8293, val_25_acc: 0.7188, val_26_acc: 0.8647, val_27_acc: 0.8618, val_28_acc: 0.9418, val_29_acc: 0.9370, loss: 113.1814 ||:   7%|7         | 29/395 [00:45<09:37,  1.58s/it]
Traceback (most recent call last):
  File "/home/lee/anaconda3/envs/dstqa/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/home/lee/anaconda3/envs/dstqa/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./dstqa/dstqa.py", line 183, in forward
    dialog_embeddings = torch.cat((dialog_elmo_embeddings, dialog_char_embeddings), dim=2)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 207 and 208 (The offending index is 0)
`

**Comment by jylee-xidian** [comment]
This project should run with allennlp==0.90, not >=0.90
